### ISSUE TITLE
Title returns nothing when it contains the character &

### ISSUE THREAD

**Issue by flowan** [pr0pz/scene-release-parser-php#10]
Hi,

When a title contains the character `&` the title will be empty.

Parsing the title for example `This.&.That.2014.etc.etc` return nothing.

A possible solution would be to add the `&` character to the title regex like so;

`const REGEX_TITLE = '([\w\\&.()-]+)';`

I tested this with a couple of scene releases and it works.

**Comment by pr0pz** [comment]
Hi flowan and thanks for the bug report.
I'll make some tests and merge the PR if everything is working as expected :)

**Comment by pr0pz** [comment]
I'm finally on it and gonna release new version soon

**Comment by pr0pz** [comment]
Fixed with newest release:

https://github.com/pr0pz/scene-release-parser-php/releases/tag/v1.5.0
