### ISSUE TITLE
Missing Audio Detection

### ISSUE THREAD

**Issue by dennisoderwald** [pr0pz/scene-release-parser-php#3]
Unfortunately, audio is not recognized here.

```
The.Italian.Job.Charlie.staubt.Millionen.ab.1969.German.DTSD.DL.2160p.UHD.US.BluRay.HDR.DV.x265-HDSource
True.Romance.1993.DC.REMASTERED.German.DTSMAD.DL.2160p.UHD.GBR.BluRay.HDR.DV.x265-HDSource
Mallrats.1995.GERMAN.DTSD.DL.2160p.UHD.BluRay.HEVC-FHC
Air.Force.One.1997.German.7.1.DTSMAD.DL.2160p.UHD.US.BluRay.HDR.DV.x265-HDSource
```

**Comment by pr0pz** [comment]
The reason should be the missing DTS definitions (DTS, DTS-HD, DTS:X ...). I'll put them in and run some tests.

True.Romance.1993.DC.REMASTERED.German.DTSMAD.DL.2160p.UHD.GBR.BluRay.HDR.DV.x265-HDSource
^ This one is mislabeled. DTSMAD doesn't exist, should only be DTSMA, will consider it.

I'll also separate the 2.1/5.1/7.1 into extra audio information.

**Comment by pr0pz** [comment]
Added a bunch of improvements for audio detection!
