### ISSUE TITLE
Missing Media Format Detection

### ISSUE THREAD

**Issue by dennisoderwald** [pr0pz/scene-release-parser-php#5]
Hey,

I'm not sure how you want to handle this, but I have two more cases here where there is no suitable media format.

```
What.A.Man.German.AC3.DVDRiP.XiD-ROOR
Intruders.Die.Aliens.Sind.Unter.Uns.1992.Uncut.German.AC3.DVDRiP.XviD
```

**Comment by pr0pz** [comment]
I see what you mean, the XiD will be fixed.
For releases without group names it's a little more complicated, since that's the one reliable thing on every release name ;) I'll give it a shot.

**Comment by pr0pz** [comment]
So, I've implemented a simple workaround for your exampl, but it's hard to make a general statement which information will be at the end of the release name if no group name is given.
