### ISSUE TITLE
Missing Media Resolution

### ISSUE THREAD

**Issue by dennisoderwald** [pr0pz/scene-release-parser-php#6]
```
Ruby.taucht.ab.2023.German.AC3.MD.DL.WEBRip.x264-omikron
Ruby.taucht.ab.2023.German.AC3.MD.WEBRip.x264-TAUCHTAUF
```

**Comment by pr0pz** [comment]
Well, the library only parses the information in the release name. If the information is missing it's only guesswork.

**Comment by dennisoderwald** [comment]
You're right about that. I would still have thought that it makes sense to agree on a default. But the more I think about it, you're probably right and a guess would be hard.

**Comment by pr0pz** [comment]
I mean, the default would be 'SD' aka 480p I think, so the lowest possible resolution. But since it's not in the release name, I would leave that interpretation to the users of the parser. It's up to you to check if the information is there ;)
