### ISSUE TITLE
Flag "NEW"

### ISSUE THREAD

**Issue by dennisoderwald** [pr0pz/scene-release-parser-php#9]
It seems that especially with German releases now and then the use of "NEW" in the title occurs, which marks a newer version.

There are also cases where "V1", "V2" etc. are really used, but I think it is difficult to make a reliable statement.

```
Barbie.2023.TS.MD.German.720p.x264-MTZ
Barbie.2023.NEW.TS.MD.German.720p.x264-MTZ
```

**Comment by pr0pz** [comment]
I've found some examples and will try to implement it if possible.

**Comment by pr0pz** [comment]
So, I tried one first implementation with New, v1, v2 and v3.
We'll have to see if it works as expected. CHeck the new release and all changes: https://github.com/pr0pz/scene-release-parser-php/releases/tag/v1.2.0
